config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :account do
    resources :orders, only: [:index]
    resources :favourites, only: [:index]
  end

end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  def self.favourites_by_user(user)
    Spree::Variant.joins(line_items: [order: [:user]])
    .where(['spree_users.id = ?', user.id])
    .where(['spree_orders.completed_at IS NOT NULL'])
    .references(:orders)
    .group('spree_variants.id')
    .order('COUNT(spree_line_items.id) DESC')
    .select('spree_variants.*')
  end

end

app/controllers/spree/account/favourites_controller.rb
module Spree
  module Account
    class FavouritesController < Spree::StoreController

      before_filter :check_logged_in_user

      def index
        @user = try_spree_current_user
        if @user
          @favourites = Spree::Variant.favourites_by_user(@user).page(params[:page] ||= 1).per(15)
        else
          unauthorized
        end
      end

      private

      def check_logged_in_user
        unless try_spree_current_user
          session[:spree_user_return_to] = account_favourites_url 
          redirect_to spree_login_path 
        end
      end

    end
  end
end

app/controllers/spree/account/orders_controller.rb
module Spree
  module Account
    class OrdersController < Spree::StoreController

      before_filter :check_logged_in_user

      def index
        @user = try_spree_current_user
        @orders = @user.orders.complete.order('completed_at desc')
      end

      def accurate_title
        Spree.t(:my_account)
      end

      private

      def check_logged_in_user
        unless try_spree_current_user
          session[:spree_user_return_to] = account_orders_url 
          redirect_to spree_login_path 
        end
      end

    end
  end
end

app/controllers/spree/store_controller_decorator.rb
Spree::StoreController.class_eval do

  before_filter :clear_stored_location_for_sign_in

  def clear_stored_location_for_sign_in
    session[:return_to] = nil
  end

end

app/views/spree/account/favourites/_table.haml
%table.favourites-summary
  %thead
    %tr
      %th.favourite-image= Spree.t(:name)
      %th.favourite-description= Spree.t(:name)
      %th.favourite-price= Spree.t(:price)
      - if SpreeMyFavourites::Config.use_quick_add_to_cart_form
        %th.favourite-add-to-cart  
  %tbody
    - favourites.each do |favourite|
      %tr
        %td.favourite-image
          - if favourite.images.length == 0
            = link_to mini_image(favourite.product), favourite.product
          - else
            = link_to image_tag(favourite.images.first.attachment.url(:mini)), favourite.product
        %td.favourite-description= favourite.name
        %td.favourite-price= display_price(favourite)
        - if SpreeMyFavourites::Config.use_quick_add_to_cart_form
          %td.favourite-add-to-cart      
            = render partial: "spree/shared/quick_cart_add_button", locals: {product: favourite.product}

app/views/spree/account/favourites/index.haml
#my-account
  = render partial: 'spree/shared/account_header', locals: {selected: :favourites}

  .account-my-favourites(data-hook="account_my_favourites")
    - if @favourites.present?
      = render partial: "spree/shared/user_favourites_table", locals: {favourites: @favourites}
      
      = paginate(@favourites)
    - else
      %p= Spree.t(:you_have_no_orders_yet)

app/views/spree/account/orders/index.haml
#my-account
  = render partial: 'spree/shared/account_header', locals: {selected: :orders}
  = render partial: 'spree/shared/user_orders'

app/views/spree/shared/_account_header.haml
%h1= accurate_title

%div{class: "account-summary well"}(data-hook="account_summary")
  %dl#user-info
    %dt= Spree.t(:email)
    %dd
      = @user.email
      (
      = link_to Spree.t(:edit), spree.edit_account_path
      )

.row
  .col-md-12
    %ul{class: "nav nav-pills"}
      %li{class: "#{selected == :orders ? 'active' : ''}"}(role="presentation")
        = link_to Spree.t(:my_orders), account_orders_path
      %li{class: "#{selected == :favourites ? 'active' : ''}"}(role="presentation")
        = link_to Spree.t(:my_favourites), account_favourites_path

app/views/spree/shared/_user_favourites_table.haml
%table{class: "table table-striped favourites-summary"}
  %thead.active
    %tr
      %th.favourite-image
      %th.favourite-description= Spree.t(:name)
      %th.favourite-sku= Spree.t(:article_number)
      %th.favourite-variant= Spree.t(:description)
      %th.favourite-price= Spree.t(:price)
      - if SpreeMyFavourites::Config.use_quick_add_to_cart_form
        %th.favourite-add-to-cart  
  %tbody
    - favourites.each do |favourite|
      %tr
        %td.favourite-image
          - if favourite.images.length == 0
            = link_to mini_image(favourite.product), favourite.product
          - else
            = link_to image_tag(favourite.images.first.attachment.url(:mini)), favourite.product
        %td.favourite-description(data-hook='favourite_name')= favourite.name
        %th.favourite-options= favourite.sku
        %th.favourite-options
          - favourite.option_values.each do |opt|
            - if not opt.presentation.to_s == "0" || opt.presentation.to_s == "null" || opt.presentation.to_s == "true" || opt.presentation.to_s == "false"
              = opt.presentation + '; '
        %td.favourite-price= display_price(favourite)
        %td.favourite-add-to-cart
          = render partial: "spree/shared/quick_cart_add_button", locals: {product: favourite.product}

app/views/spree/shared/_user_orders.haml
.account-my-orders-tab(data-hook="account_my_orders_tab")
  - if @orders.present?
    %table.order-summary{class: "table table-striped "}
      %thead.active
        %tr
          %th.order-number= I18n.t(:number, :scope => 'activerecord.attributes.spree/order')
          %th.order-date= Spree.t(:date)
          %th.order-status= Spree.t(:status)
          %th.order-payment-state= Spree.t(:payment_state)
          %th.order-shipment-state= Spree.t(:shipment_state)
          %th.order-total= Spree.t(:total)
      %tbody
        - @orders.each do |order|
          %tr
            %td.order-number= link_to order.number, order_url(order)
            %td.order-date= l order.completed_at.to_date
            %td.order-status= Spree.t("order_state.#{order.state}").titleize
            %td.order-payment-state= Spree.t("payment_states.#{order.payment_state}").titleize if order.payment_state
            %td.order-shipment-state= Spree.t("shipment_states.#{order.shipment_state}").titleize if order.shipment_state
            %td.order-total= order.display_total
  - else
    %p{class: "alert alert-info"}= Spree.t(:you_have_no_orders_yet)

app/views/spree/users/show.haml
#my-account
  = render partial: 'spree/shared/account_header', locals: {selected: :orders}
  = render partial: 'spree/shared/user_orders'

.account-my-orders(data-hook="account_my_orders")